DEFINE DATA_TBSP_NAME = &&1
DEFINE DATA_TBSP_LOCATION =  &&2
DEFINE EXT = '.dbf'
DEFINE ADD1 = '_DATA'
DEFINE ADD2 = '_IDX'

CREATE SMALLFILE TABLESPACE &&DATA_TBSP_NAME&ADD1
    DATAFILE '&&DATA_TBSP_LOCATION\&&DATA_TBSP_NAME&ADD1&EXT'
        SIZE 10M AUTOEXTEND ON NEXT 10 MAXSIZE 5368709120 
        EXTENT MANAGEMENT LOCAL SEGMENT SPACE 
        MANAGEMENT AUTO;
PROMPT 'TABLESPACE_DATA WAS CREATED'

CREATE SMALLFILE TABLESPACE &&DATA_TBSP_NAME&ADD2
    DATAFILE '&&DATA_TBSP_LOCATION\&&DATA_TBSP_NAME&ADD2&EXT'
        SIZE 10M AUTOEXTEND ON NEXT 10 MAXSIZE 5368709120 
        EXTENT MANAGEMENT LOCAL SEGMENT SPACE 
        MANAGEMENT AUTO;
PROMPT 'TABLESPACE_IDX WAS CREATED'